### PR TITLE
[IMP] component: allow subscribing to scheduler updates

### PR DESCRIPTION
**Pull request by seb-odoo**
Please consider the following PR, to properly subscribe to scheduler updates.

### CODE REVIEW

**Comment by seb-odoo** [comment]
Ready for review, but I'm not particularly happy about the part where I copied makeDeferred into scheduler, if you have a better suggestion.

**Comment by gdeb** [comment]
Could you tell me what problem you are trying to solve? I am not fond of changing that much the code for the sake of tests

**Comment by seb-odoo** [comment]
It is for test, with the current suggested helper, I could not find a way to make sure the queue was "busy" at least once between when I called the helper and when it resolved, which would ensure me that something was done and that it wasn't just a dummy call.

I came close, but I had cases where the queue was initially empty, then a task was done, and then queue was empty again before I could notice it. The promise would resolve, but I would consider it as a dummy call when in fact it wasn't.

I don't have the issue anymore with the current PR.

**Comment by ged-odoo** [comment]
sorry, but I think that a better solution is to to it externally like we talked.

**Pull request closed without merging**
