### PR TITLE
[IMP] router: allow query string in paths

### PR DESCRIPTION
**Pull request by dupski**
We're starting to use OWL for modern front-end development, however the router did not allow navigating to paths with a query string in the URL, e.g.

```js
router.navigate({ path: '/tasks/search?query=test&count=20' })
```
did not match the `/tasks/search` path.

Now it does :)

I've added tests. Let me know if you need anything further.

### CODE REVIEW

**Comment by dupski** [comment]
Hey folks. Any chance someone could take a look at this PR? Happy to make any changes needed.

I would like to submit an Odoo experience talk on building modern front-end apps (that sit on top of Odoo) with OWL, so it would be nice if the router supported query parameters :)

**Comment by dupski** [comment]
Ah, I will take a look at the conflicts

**Comment by ged-odoo** [comment]
oh sorry for taking so long @dupski . Yes, we actually fixed some issues recently. If it solves your issue, great, otherwise, we will have a look at your PR.

**Comment by dupski** [comment]
Hi @ged-odoo - sadly the new version still doesn't work with query strings so I've updated this PR for the new version.

Please could someone take a look and merge when happy. Cheers!

**Comment by dupski** [comment]
Please can someone look at this PR @ged-odoo - currently it is impossible to use query strings (e.g. ?status=test) with the built-in router, which is very limiting. This PR does not do matching on query strings, it simply allows them to be used.

**Comment by ged-odoo** [comment]
@dupski Sorry again for the long delay. The PR looks totally reasonable, and I am willing to merge it (could you squash the commits before?). However, I have been informed that I cannot accept any external contribution without a CLA (contributor license agreement). I think it is excessive, but I have no say on that matter.  Would you mind making a PR on odoo main repository (https://github.com/odoo/odoo) with a simple commit to add you on the list of contributors? (see https://github.com/odoo/odoo/blob/14.0/doc/cla/sign-cla.md for more detail, or check https://github.com/odoo/odoo/commits/14.0/doc/cla/individual for some examples).

Don't hesitate to ping me on that PR so I can accept it immediately.  Thank you for your interest in owl :)

**Pull request closed without merging**
